BINANCE_MODE=live
BINANCE_MARKET_TYPE=futures

BINANCE_KEY_TYPE=rsa
BINANCE_API_KEY=sZU73K8oQP8nmDMKZy3YRrHVIBxHyTQ0vEzVKnQtKeTUnOXG6JbMJjwRIdGKXtBs
BINANCE_PRIVATE_KEY_PATH=./private_key.pem

AUTO_SCALPING=true
AUTO_TRADE_ENABLED=true
DRY_RUN=false

ORDER_USDT=2.5
DEFAULT_LEVERAGE=3

MAX_OPEN_POSITIONS=2

SCALPING_INTERVAL=20
SCALPING_TIMEFRAME=1m

EMA_FAST=5
EMA_SLOW=13

BUY_RSI=51
SELL_RSI=49

VOLUME_MULTIPLIER=0.7
FAST_SIGNAL_MODE=true

TRADE_SYMBOL=SOLUSDT

SCALPING_SYMBOLS=SOLUSDT,DOGEUSDT,1000PEPEUSDT,LINKUSDT,AVAXUSDT

ALLOW_SHORT=true

TP_PERCENT=0.3
SL_PERCENT=0.25

MAX_HOLD_SECONDS=300
FORCE_CLOSE_PROFIT_PERCENT=0.15BINANCE_MODE=live
BINANCE_MARKET_TYPE=futures

BINANCE_KEY_TYPE=rsa
BINANCE_API_KEY=sZU73K8oQP8nmDMKZy3YRrHVIBxHyTQ0vEzVKnQtKeTUnOXG6JbMJjwRIdGKXtBs
BINANCE_PRIVATE_KEY_PATH=./private_key.pem

AUTO_SCALPING=true
AUTO_TRADE_ENABLED=true
DRY_RUN=false

ORDER_USDT=2.5
DEFAULT_LEVERAGE=3

MAX_OPEN_POSITIONS=2

SCALPING_INTERVAL=20
SCALPING_TIMEFRAME=1m

EMA_FAST=5
EMA_SLOW=13

BUY_RSI=51
SELL_RSI=49

VOLUME_MULTIPLIER=0.7
FAST_SIGNAL_MODE=true

TRADE_SYMBOL=SOLUSDT

SCALPING_SYMBOLS=SOLUSDT,DOGEUSDT,1000PEPEUSDT,LINKUSDT,AVAXUSDT

ALLOW_SHORT=true

TP_PERCENT=0.3
SL_PERCENT=0.25

MAX_HOLD_SECONDS=300
FORCE_CLOSE_PROFIT_PERCENT=0.15BINANCE_MODE=live
BINANCE_MARKET_TYPE=futures

BINANCE_KEY_TYPE=rsa
BINANCE_API_KEY=sZU73K8oQP8nmDMKZy3YRrHVIBxHyTQ0vEzVKnQtKeTUnOXG6JbMJjwRIdGKXtBs
BINANCE_PRIVATE_KEY_PATH=./private_key.pem

AUTO_SCALPING=true
AUTO_TRADE_ENABLED=true
DRY_RUN=false

ORDER_USDT=2.5
DEFAULT_LEVERAGE=3

MAX_OPEN_POSITIONS=2

SCALPING_INTERVAL=20
SCALPING_TIMEFRAME=1m

EMA_FAST=5
EMA_SLOW=13

BUY_RSI=51
SELL_RSI=49

VOLUME_MULTIPLIER=0.7
FAST_SIGNAL_MODE=true

TRADE_SYMBOL=SOLUSDT

SCALPING_SYMBOLS=SOLUSDT,DOGEUSDT,1000PEPEUSDT,LINKUSDT,AVAXUSDT

ALLOW_SHORT=true

TP_PERCENT=0.3
SL_PERCENT=0.25

MAX_HOLD_SECONDS=300
FORCE_CLOSE_PROFIT_PERCENT=0.15